//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit_logs
    {
        public int id { get; set; }
        public string application { get; set; }
        public string description { get; set; }
        public Nullable<int> party_id { get; set; }
        public string additional_info { get; set; }
        public Nullable<int> audit_log_type_id { get; set; }
        public Nullable<int> event_record_id { get; set; }
        public string event_record_type { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
