//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit_log_items
    {
        public int id { get; set; }
        public Nullable<int> audit_log_id { get; set; }
        public Nullable<int> audit_log_item_type_id { get; set; }
        public string audit_log_item_value { get; set; }
        public string audit_log_item_old_value { get; set; }
        public string description { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
