//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Collections.Generic;
    
    public partial class capability
    {
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<int> capability_type_id { get; set; }
        public Nullable<int> capability_resource_id { get; set; }
        public string capability_resource_type { get; set; }
        public Nullable<int> scope_type_id { get; set; }
        public string scope_query { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
