//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id { get; set; }
        public string commentor_name { get; set; }
        public string email { get; set; }
        public string comment1 { get; set; }
        public Nullable<int> approved { get; set; }
        public Nullable<System.DateTime> approved_at { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> commented_record_id { get; set; }
        public string commented_record_type { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
