//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuration_item_types
    {
        public int id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> lft { get; set; }
        public Nullable<int> rgt { get; set; }
        public Nullable<int> precedence { get; set; }
        public string description { get; set; }
        public string internal_identifier { get; set; }
        public Nullable<bool> allow_user_defined_options { get; set; }
        public Nullable<bool> is_multi_optional { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
