//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int id { get; set; }
        public Nullable<int> contact_mechanism_id { get; set; }
        public string contact_mechanism_type { get; set; }
        public Nullable<bool> is_primary { get; set; }
        public string external_identifier { get; set; }
        public string external_id_source { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public string contact_record_type { get; set; }
        public Nullable<int> contact_record_id { get; set; }
    }
}
