//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Collections.Generic;
    
    public partial class content_versions
    {
        public int id { get; set; }
        public Nullable<int> content_id { get; set; }
        public Nullable<int> version { get; set; }
        public string title { get; set; }
        public string permalink { get; set; }
        public string excerpt_html { get; set; }
        public string body_html { get; set; }
        public Nullable<int> created_by_id { get; set; }
        public Nullable<int> updated_by_id { get; set; }
        public string internal_identifier { get; set; }
        public Nullable<bool> display_title { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string versioned_type { get; set; }
    }
}
