//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency
    {
        public int id { get; set; }
        public string name { get; set; }
        public string definition { get; set; }
        public string internal_identifier { get; set; }
        public string numeric_code { get; set; }
        public string major_unit_symbol { get; set; }
        public string minor_unit_symbol { get; set; }
        public string ratio_of_minor_unit_to_major_unit { get; set; }
        public string postfix_label { get; set; }
        public Nullable<System.DateTime> introduction_date { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
