//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Collections.Generic;
    
    public partial class descriptive_assets
    {
        public int id { get; set; }
        public Nullable<int> view_type_id { get; set; }
        public string internal_identifier { get; set; }
        public string description { get; set; }
        public string external_identifier { get; set; }
        public string external_id_source { get; set; }
        public Nullable<int> described_record_id { get; set; }
        public string described_record_type { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
