//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Collections.Generic;
    
    public partial class file_assets
    {
        public int id { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public string directory { get; set; }
        public string data_file_name { get; set; }
        public string data_content_type { get; set; }
        public Nullable<int> data_file_size { get; set; }
        public Nullable<System.DateTime> data_updated_at { get; set; }
        public string width { get; set; }
        public string height { get; set; }
        public string scoped_by { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
