//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Collections.Generic;
    
    public partial class file_asset_holders
    {
        public int id { get; set; }
        public Nullable<int> file_asset_id { get; set; }
        public Nullable<int> file_asset_holder_id { get; set; }
        public string file_asset_holder_type { get; set; }
        public string scoped_by { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
