//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_zones
    {
        public int id { get; set; }
        public Nullable<int> geo_country_id { get; set; }
        public string zone_code { get; set; }
        public string zone_name { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
