//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Collections.Generic;
    
    public partial class individual
    {
        public int id { get; set; }
        public Nullable<int> party_id { get; set; }
        public string current_last_name { get; set; }
        public string current_first_name { get; set; }
        public string current_middle_name { get; set; }
        public string current_personal_title { get; set; }
        public string current_suffix { get; set; }
        public string current_nickname { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<int> weight { get; set; }
        public string mothers_maiden_name { get; set; }
        public string marital_status { get; set; }
        public string social_security_number { get; set; }
        public Nullable<int> current_passport_number { get; set; }
        public Nullable<System.DateTime> current_passport_expire_date { get; set; }
        public Nullable<int> total_years_work_experience { get; set; }
        public string comments { get; set; }
        public string encrypted_ssn { get; set; }
        public string temp_ssn { get; set; }
        public string salt { get; set; }
        public string ssn_last_four { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
