//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Collections.Generic;
    
    public partial class party_relationships
    {
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<int> party_id_from { get; set; }
        public Nullable<int> party_id_to { get; set; }
        public Nullable<int> role_type_id_from { get; set; }
        public Nullable<int> role_type_id_to { get; set; }
        public Nullable<int> status_type_id { get; set; }
        public Nullable<int> priority_type_id { get; set; }
        public Nullable<int> relationship_type_id { get; set; }
        public Nullable<System.DateTime> from_date { get; set; }
        public Nullable<System.DateTime> thru_date { get; set; }
        public string external_identifier { get; set; }
        public string external_id_source { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
