//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Collections.Generic;
    
    public partial class party_fixed_asset_assignments
    {
        public int id { get; set; }
        public Nullable<int> party_id { get; set; }
        public Nullable<int> fixed_asset_id { get; set; }
        public Nullable<System.DateTime> assigned_from { get; set; }
        public Nullable<System.DateTime> assigned_thru { get; set; }
        public Nullable<int> allocated_cost_money_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
