//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Collections.Generic;
    
    public partial class published_elements
    {
        public int id { get; set; }
        public Nullable<int> published_website_id { get; set; }
        public Nullable<int> published_element_record_id { get; set; }
        public string published_element_record_type { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<int> published_by_id { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
