//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReferenceEntities : DbContext
    {
        public ReferenceEntities()
            : base("name=ReferenceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<application> applications { get; set; }
        public virtual DbSet<audit_log_item_types> audit_log_item_types { get; set; }
        public virtual DbSet<audit_log_items> audit_log_items { get; set; }
        public virtual DbSet<audit_log_types> audit_log_types { get; set; }
        public virtual DbSet<audit_logs> audit_logs { get; set; }
        public virtual DbSet<capability> capabilities { get; set; }
        public virtual DbSet<capability_accessors> capability_accessors { get; set; }
        public virtual DbSet<capability_types> capability_types { get; set; }
        public virtual DbSet<capable_models> capable_models { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<category_classifications> category_classifications { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<compass_ae_instance_party_roles> compass_ae_instance_party_roles { get; set; }
        public virtual DbSet<compass_ae_instances> compass_ae_instances { get; set; }
        public virtual DbSet<configuration_item_types> configuration_item_types { get; set; }
        public virtual DbSet<configuration_item_types_configuration_options> configuration_item_types_configuration_options { get; set; }
        public virtual DbSet<configuration_items> configuration_items { get; set; }
        public virtual DbSet<configuration_options> configuration_options { get; set; }
        public virtual DbSet<configuration> configurations { get; set; }
        public virtual DbSet<contact_purposes> contact_purposes { get; set; }
        public virtual DbSet<contact_types> contact_types { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<content_versions> content_versions { get; set; }
        public virtual DbSet<content> contents { get; set; }
        public virtual DbSet<currency> currencies { get; set; }
        public virtual DbSet<delayed_jobs> delayed_jobs { get; set; }
        public virtual DbSet<descriptive_assets> descriptive_assets { get; set; }
        public virtual DbSet<document_types> document_types { get; set; }
        public virtual DbSet<documented_items> documented_items { get; set; }
        public virtual DbSet<document> documents { get; set; }
        public virtual DbSet<email_addresses> email_addresses { get; set; }
        public virtual DbSet<entity_party_roles> entity_party_roles { get; set; }
        public virtual DbSet<facility> facilities { get; set; }
        public virtual DbSet<facility_types> facility_types { get; set; }
        public virtual DbSet<file_asset_holders> file_asset_holders { get; set; }
        public virtual DbSet<file_assets> file_assets { get; set; }
        public virtual DbSet<fixed_asset_party_roles> fixed_asset_party_roles { get; set; }
        public virtual DbSet<fixed_asset_types> fixed_asset_types { get; set; }
        public virtual DbSet<fixed_assets> fixed_assets { get; set; }
        public virtual DbSet<generated_items> generated_items { get; set; }
        public virtual DbSet<geo_countries> geo_countries { get; set; }
        public virtual DbSet<geo_zones> geo_zones { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<individual> individuals { get; set; }
        public virtual DbSet<job_trackers> job_trackers { get; set; }
        public virtual DbSet<money> moneys { get; set; }
        public virtual DbSet<note_types> note_types { get; set; }
        public virtual DbSet<note> notes { get; set; }
        public virtual DbSet<notification_types> notification_types { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<organization> organizations { get; set; }
        public virtual DbSet<party> parties { get; set; }
        public virtual DbSet<party_fixed_asset_assignments> party_fixed_asset_assignments { get; set; }
        public virtual DbSet<party_relationships> party_relationships { get; set; }
        public virtual DbSet<party_roles> party_roles { get; set; }
        public virtual DbSet<phone_numbers> phone_numbers { get; set; }
        public virtual DbSet<postal_addresses> postal_addresses { get; set; }
        public virtual DbSet<preference_options> preference_options { get; set; }
        public virtual DbSet<preference_types> preference_types { get; set; }
        public virtual DbSet<preference> preferences { get; set; }
        public virtual DbSet<published_elements> published_elements { get; set; }
        public virtual DbSet<published_websites> published_websites { get; set; }
        public virtual DbSet<relationship_types> relationship_types { get; set; }
        public virtual DbSet<report> reports { get; set; }
        public virtual DbSet<role_types> role_types { get; set; }
        public virtual DbSet<scope_types> scope_types { get; set; }
        public virtual DbSet<security_roles> security_roles { get; set; }
        public virtual DbSet<session> sessions { get; set; }
        public virtual DbSet<status_applications> status_applications { get; set; }
        public virtual DbSet<tagging> taggings { get; set; }
        public virtual DbSet<tag> tags { get; set; }
        public virtual DbSet<theme> themes { get; set; }
        public virtual DbSet<tracked_status_types> tracked_status_types { get; set; }
        public virtual DbSet<tree_menu_node_defs> tree_menu_node_defs { get; set; }
        public virtual DbSet<unit_of_measurements> unit_of_measurements { get; set; }
        public virtual DbSet<user_preferences> user_preferences { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<valid_configurations> valid_configurations { get; set; }
        public virtual DbSet<valid_documents> valid_documents { get; set; }
        public virtual DbSet<valid_note_types> valid_note_types { get; set; }
        public virtual DbSet<valid_preference_types> valid_preference_types { get; set; }
        public virtual DbSet<view_types> view_types { get; set; }
        public virtual DbSet<website_hosts> website_hosts { get; set; }
        public virtual DbSet<website_inquiries> website_inquiries { get; set; }
        public virtual DbSet<website_nav_items> website_nav_items { get; set; }
        public virtual DbSet<website_navs> website_navs { get; set; }
        public virtual DbSet<website_party_roles> website_party_roles { get; set; }
        public virtual DbSet<website_section_contents> website_section_contents { get; set; }
        public virtual DbSet<website_section_versions> website_section_versions { get; set; }
        public virtual DbSet<website_sections> website_sections { get; set; }
        public virtual DbSet<website> websites { get; set; }
        public virtual DbSet<schema_migrations> schema_migrations { get; set; }
    }
}
