//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Collections.Generic;
    
    public partial class theme
    {
        public int id { get; set; }
        public Nullable<int> website_id { get; set; }
        public string name { get; set; }
        public string theme_id { get; set; }
        public string author { get; set; }
        public Nullable<int> version { get; set; }
        public string homepage { get; set; }
        public string summary { get; set; }
        public Nullable<int> active { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
