//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Collections.Generic;
    
    public partial class tree_menu_node_defs
    {
        public int id { get; set; }
        public string node_type { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> lft { get; set; }
        public Nullable<int> rgt { get; set; }
        public string menu_short_name { get; set; }
        public string menu_description { get; set; }
        public string text { get; set; }
        public string icon_url { get; set; }
        public string target_url { get; set; }
        public string resource_class { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
