//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Collections.Generic;
    
    public partial class valid_preference_types
    {
        public int id { get; set; }
        public Nullable<int> preference_type_id { get; set; }
        public Nullable<int> preferenced_record_id { get; set; }
        public string preferenced_record_type { get; set; }
    }
}
