//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Collections.Generic;
    
    public partial class valid_documents
    {
        public int id { get; set; }
        public Nullable<int> document_id { get; set; }
        public Nullable<int> documented_model_id { get; set; }
        public string documented_model_type { get; set; }
    }
}
