//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Collections.Generic;
    
    public partial class website_sections
    {
        public int id { get; set; }
        public string title { get; set; }
        public string type { get; set; }
        public Nullable<int> website_id { get; set; }
        public string path { get; set; }
        public string permalink { get; set; }
        public string layout { get; set; }
        public Nullable<bool> in_menu { get; set; }
        public Nullable<int> position { get; set; }
        public Nullable<bool> use_markdown { get; set; }
        public string internal_identifier { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<bool> render_base_layout { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> lft { get; set; }
        public Nullable<int> rgt { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
