//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanaErp.Core.Models.Reference
{
    using System;
    using System.Collections.Generic;
    
    public partial class website_nav_items
    {
        public int id { get; set; }
        public Nullable<int> website_nav_id { get; set; }
        public string title { get; set; }
        public string url { get; set; }
        public Nullable<int> position { get; set; }
        public Nullable<int> linked_to_item_id { get; set; }
        public string linked_to_item_type { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> lft { get; set; }
        public Nullable<int> rgt { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    }
}
